### PR TITLE
Fixed quickstart script and merged upstream

### PR DESCRIPTION
**Pull request by ortix**
There were a couple of small issues in the quickstart script.

First, the quickstart script was referring to the `cert-issuer.yml` file, which had been moved to a helm template. I have commented the line.

Finally, the helm incubator url has been deprecated. I have updated that url

### CODE REVIEW

**Comment by bartversluijs** [comment]
Ah nice catch! Thanks!
Didn't notice it and didn't try the quickstart after that change.
And thanks for updating the Helm incubator url.

Haven't tested it with openBalena version v3.2.1 yet, because I know that from openBalena v3.2.0, it uses a new endpoint (`tunnel.<domain>`).

I'm leaving this open until anyone can confirm that it works or not. If not, this will have to be added to the ingress probably.

**Comment by ortix** [comment]
I am still in the process of getting the whole stack up and running with my devices so I will probably hit this issue soon enough.

I assume the `tunnel.<domain>` is used for tunneling ssh connections to the IoT devices?

**Comment by bartversluijs** [comment]
[This is the PR regarding the change](https://github.com/balena-io/open-balena/pull/101), so it seems like it has to do with the `balena tunnel` command indeed! (I see now that I've already commented in that PR for more information...)

You've to update Balena CLI to v12.38.5 when testing it, so it'll use the `tunnel.<domain>` endpoint.

**Comment by bartversluijs** [comment]
I'll close this PR because this will be fixed by the new Helm chart release. Was too late for merging it, because of new commits on your branch, but thanks for the change!

**Pull request closed without merging**
